### ISSUE TITLE
后台接收ajax有问题

### ISSUE THREAD

**Issue by BigBugaboo** [Roiko97/-Goods#1]
@Roiko97 

ajax包里的insertOperating显示错误，无论是传map还是键值对，都无法成功，前台显示500，连接失败。
at com.jung.ajax.insertOperating.doInsert(insertOperating.java:35)
	at com.jung.communicate.WritingCommunicationServlet.doGet(WritingCommunicationServlet.java:45)
	at com.jung.communicate.WritingCommunicationServlet.doPost(WritingCommunicationServlet.java:51)

**Comment by Roiko97** [comment]
insertOperating 是普通的类，无法直接访问
你可以访问的应该是communicate包下的[ReplyServlet\WritingCommunicationServlet\WritingLostAndFoundServlet]
